apiVersion: v1
kind: Service
metadata:
  name: learning-app-service
spec:
  selector:
    app: learning-app
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: NodePort
